all:
  children:
    yandex_cloud:
      hosts:
        vm:
          ansible_host: "{{ lookup('env', 'VM_HOST') }}"
          ansible_user: "{{ lookup('env', 'VM_USER') | default('ubuntu', true) }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE') | default('~/.ssh/id_rsa', true) }}"
          ansible_python_interpreter: /usr/bin/python3
