apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moscow-time-app.fullname" . }}-secret
  labels:
    {{- include "moscow-time-app.labels" . | nindent 4 }}
type: Opaque
data:
  MY_PASS: {{ .Values.secret.password | b64enc }}
  MY_USER: {{ .Values.secret.username | b64enc }}
  APP_SECRET: {{ .Values.secret.appSecret | b64enc }}
